version: '3.9'
services:
  reverse-proxy:
    image: traefik:2.6
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=true"
      - "--entrypoints.frontend.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: ../backend
    volumes:
      - ../backend/app/src:/app/src
    environment:
      - PORT=${BACKEND_PORT}
    labels:
      traefik.enable: true
      traefik.http.routers.backend.rule: PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: ${BACKEND_PORT}

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/app/src:/app/src
    environment:
      - PORT=${FRONTEND_PORT}
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.entrypoints: frontend
      traefik.http.routers.frontend.rule: "!PathPrefix(`/api`)"
      traefik.http.services.frontend.loadbalancer.server.port: ${FRONTEND_PORT}